# Generated by Django 4.1.7 on 2023-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='ваш возраст'),
        ),
        migrations.AlterField(
            model_name='username',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Ваш номер телефона'),
        ),
    ]
