# Generated by Django 4.1.7 on 2023-03-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historytransfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytransfer',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
